### ISSUE TITLE
Order of operation with fixes

### ISSUE THREAD

**Issue by nnellans** [Azure/grept#29] opened 2024-01-21 03:05 UTC
@lonegunmanb - First off, I love the idea of this tool, and I'm excited to see where it goes.

I'm trying to use the fix for `local_file` to create some files in my repos.  However, it appears that the full folder path needs to exist for the `local_file` fix to work.  In other words, if I'm trying to create a `.github/workflows/file.yaml` in a repo, and that repo doesn't have a `.github` folder and a `workflows` subfolder already, then I get an error from grept.

So, to get around this I tried to create a rule for `dir_exist` and use it to run a `local_shell` fix that would run a simple `mkdir` command.

This works great, but only when grept decides to run the `local_shell` fix before it runs the `local_file` fix.  In doing some testing, sometimes it will, and sometimes it won't.

I tried adding the terraform `depends_on` argument to the fix, but that made grept throw an error.

Is there a way to specify order of operations, or specify dependencies for the fixes?

**Comment by lonegunmanb** [comment] 2024-01-22 02:28
Thanks @nnellans for your support, I'm glad that you like `grept`'s idea, it means a lot to me.

I like this `depends_on` idea since I've also met the very similar issue.

>However, it appears that the full folder path needs to exist for the `local_file` fix to work. In other words, if I'm trying to create a `.github/workflows/file.yaml` in a repo, and that repo doesn't have a `.github` folder and a workflows subfolder already, then I get an error from grept

The issue you described looks like a bug to me since `local_file` is designed to create all sub folders for you. We have a corresponding [unit test](https://github.com/Azure/grept/blob/main/pkg/fix_local_file_test.go#L84-L109). I'll verify this issue on my side, whilst would you please share the error message with me returned by `grept`? Thanks!

**Comment by lonegunmanb** [comment] 2024-01-22 10:19
Hi @nnellans I found that the `afero.Memfs` I used in the unit test has different behavior than `OsFs`, I've rewrite the unit test and fixed the bug you've met, would you please install the latest version and try again? Thanks!

**Comment by nnellans** [comment] 2024-01-22 13:46
Thanks for the response.  The `local_file` fix is now giving me a "permission denied" error when it tries to create the `.github/workflows` directory.  [GitHub Workflow Run](https://github.com/nnellansorg/azure-grept/actions/runs/7612046235).

Do I need to run `sudo grept` instead of just `grept` maybe?

**Comment by lonegunmanb** [comment] 2024-01-23 02:58
Hi @nnellans could run `mkdir .github./workflows` in the session you called `grept`?

**Comment by nnellans** [comment] 2024-01-23 03:24
I am running grept from GitHub Actions, on `ubuntu-latest` runner, and using a simple `run` step.

If I add a command for `mkdir -p .github/workflows` and put that right before the grept command, then it works fine.  However, if I simply try to run the `grep apply --auto` command and let the `local_file` fix attempt to create the full path, then I get the error mentioned above.

**Comment by lonegunmanb** [comment] 2024-01-23 04:46
Many thanks @nnellans , I'll try to reproduce this issue.

**Comment by nnellans** [comment] 2024-01-23 13:41
Here's my [workflow](https://github.com/nnellansorg/azure-grept/blob/main/.github/workflows/grept.yaml).

**Comment by lonegunmanb** [comment] 2024-01-24 07:17
Hi @nnellans I've merged another pr now [a toy workflow](https://github.com/lonegunmanb/test-grept-local-file/blob/main/.github/workflows/grept.yaml) can work now.

You can change your workflow by installing `grept` like this:

```shell
go install github.com/Azure/grept@ca36e4333ddf2dbc5371c78bf7b0fe51e17e6d83
```

This latest version should solve your issue.

A big THANKS for reporting this issue to us!

**Comment by nnellans** [comment] 2024-01-25 01:32
Works like a charm now!  Thank you very much!

**Closed** 2024-01-25 01:32 UTC

**Comment by lonegunmanb** [comment] 2024-01-25 06:43
Hey @nnellans I'm glad that this tool could help you, if you meet any further issues please feel free to report them here, thanks again for your support!
